source/accounts/urls.py
from django.urls import path, include
from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>", accounts_views.UserDetailView.as_view(), name="profile"),
    path('<int:pk>/change/', accounts_views.UserChangeView.as_view(), name='change'),
    path("<int:pk>/change-password/", accounts_views.UserPasswordChangeView.as_view(), name="change_password")
]

source/tractor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views

app_name = "webapp"

urlpatterns = [
    path("", webapp_views.IndexView.as_view(), name="index"),
    path("crane/", webapp_views.CraneView.as_view(), name="crane"),
    path("excavator/", webapp_views.ExcavatorView.as_view(), name="excavator"),
    path("truck/", webapp_views.TruckView.as_view(), name="truck"),
    path("lorry/", webapp_views.LorryView.as_view(), name="lorry"),
    path("small_truck/", webapp_views.SmallTrackView.as_view(), name="small_truck"),
    path("manipulator/", webapp_views.ManipulatorTrackView.as_view(), name="manipulator"),
    path("loader/", webapp_views.LoaderTrackView.as_view(), name="loader"),
    path("build_technique/", webapp_views.BuildTechniqueView.as_view(), name="build_technique"),
    path("tractor/", webapp_views.TractorView.as_view(), name="tractor"),
    path("other_technique/", webapp_views.OtherTechniqueView.as_view(), name="other_technique"),
    path("technique/create/", webapp_views.TechniqueCreateView.as_view(), name="technique_create"),
    path("technique/<int:pk>/change-status/", webapp_views.TechniqueStatusChangeView.as_view(), name="change_status"),
    path("technique/<int:pk>/", webapp_views.TechniqueDetailView.as_view(), name="technique_detail"),
    path("technique/<int:pk>/edit/", webapp_views.TechniqueEditView.as_view(), name="technique_edit"),
    path("technique/<int:pk>/delete/", webapp_views.TechniqueDeleteView.as_view(), name="technique_delete"),
    path("technique/<int:pk>/order/create/", webapp_views.OrderCreateView.as_view(), name="order_create"),
    path("technique/<int:pk>/order/delete/", webapp_views.OrderDeleteView.as_view(), name="order_delete"),
    path("technique/<int:pk>/comment/create/", webapp_views.CommentCreateView.as_view(), name="comment_create")
]

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    phone_number = models.CharField(max_length=150, verbose_name="Контактный телефон")
    text = models.TextField(max_length=3000, null=True, verbose_name="Text")

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=150, required=False, label="Email")
    birth_date = forms.DateField(label='Дата рождения', required=False,)
    avatar = forms.ImageField(label='Аватар', required=False,)
    phone_number = forms.CharField(max_length=150, label="Контактный телефон")
    text = forms.CharField(max_length=3000, label="Text", required=False,)

    class Meta(UserCreationForm.Meta):
        fields = ["username", "avatar", "first_name", "last_name", "phone_number", "email",
                  "birth_date", "password1", "password2", "text"]


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name", 'email']
        labels = {'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

source/accounts/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from accounts.forms import RegistrationForm, ProfileChangeForm, UserChangeForm
from django.urls import reverse

from accounts.models import Profile


class RegisterView(CreateView):
    model = get_user_model()
    template_name = "registration/register.html"
    form_class = RegistrationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect("webapp:index")


class UserDetailView(UserPassesTestMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def test_func(self):
        return self.request.user == self.get_object() or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        advertiser = self.object.techniques.order_by('is_active')
        paginator = Paginator(advertiser, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['advertiser'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UsersView(ListView):
    model = get_user_model()
    template_name = "ads/index.html"
    context_object_name = "users"
    ordering = ["username"]


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object() or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def test_func(self):
        return self.request.user.pk == self.kwargs["pk"] or self.request.user.is_superuser

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Редоктирование{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Редактировать профайл</h1>
        <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            {{ profile_form|crispy }}
            <button>Редактировать</button>
        </form>
    {% endif %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}User {{ user_obj.username }}{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user == user_obj %}
            <h1>Ваш профиль:</h1>
            <div class="user_avatar">
                {% if user_obj.profile.avatar %}
                    <img src="{{ user_obj.profile.avatar.url }}" width="150" height="150" alt="user picture">
                {% else %}
                    <img src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-vector-260nw-1725655669.jpg"
                           width="150" height="150" alt="">
                {% endif %}
            </div>
            <div class="user_data">
                Логин: <b>{{ user_obj.username }}</b><br>
                Имя: <b>{{ user_obj.first_name }}</b><br>
                Фамилия: <b>{{ user_obj.last_name }}</b><br>
                Дата рождения: <b>{{ user_obj.profile.birth_date }}</b><br>
                Контакный номер: <b>{{ user_obj.profile.phone_number }}</b><br>
                Email: <b>{{ user_obj.email }}</b><br>
                Обо мне: <b>{{ user_obj.profile.text }}</b><br>
            </div>
                <div class="profile_btn">
                    <a href="{% url 'accounts:change' user_obj.pk %}">Редактировать данные</a><br>
                    <a style="color: green" href="{% url 'accounts:change_password' user_obj.pk %}">Изменить пароль</a>
                </div>

            <h2>Ваши объявления:</h2>
            {% for technique in user_obj.techniques.all %}
                <div class="profile_technique">
                    <div class="accordion" id="accordionExample">
                      <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                {{ technique.name }}{{ technique.price }} тенге за {{ technique.price_description }} {{ technique.status }}
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                          <div class="accordion-body">
                          <a href="{% url "webapp:technique_detail" technique.pk %}">Перейти к объявлению</a>
                              {% for order in technique.orders.all %}
                                  <div class="profile_order">
                                      Заявка от: <strong class="profile_order_data">{{ order.author.username }}</strong>
                                      Телефон: <strong class="profile_order_data">{{ order.author.profile.phone_number }}</strong>
                                      Начало: <strong class="profile_order_data">{{ order.start_time }}</strong>
                                      Конец: <strong class="profile_order_data">{{ order.end_time }}</strong>
                                      <code>Предлагаемая цена: {{ order.offered_price }}</code>
                                      <p class="profile_order_text">
                                          Описание: <strong class="profile_order_data">{{ order.description }}</strong>
                                          {% if request.user.username == user_obj.username %}
                                            <form action="{% url "webapp:order_delete" technique.pk %}">
                                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal4">
                                                  Удалить
                                                </button>
                                            </form>

                                            <!-- Modal -->
                                            <div class="modal fade" id="exampleModal4" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                              <div class="modal-dialog">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Вы хотите удалить заявку?</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                                    <form action="{% url "webapp:order_delete" technique.pk %}" method="post">
                                                        {% csrf_token %}
                                                        <button class="btn btn-primary btn-danger">Да</button>
                                                    </form>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                        {% endif %}
                                      </p><hr>
                                  </div>
                              {% endfor %}
                          </div>
                        </div>
                      </div>
                    </div>

                </div>

            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Смена пароля</h1>
        <form action="{% url "accounts:change_password" request.user.pk %}" method="post">
            {% csrf_token %}
                {{ form|crispy }}
            <button>Изменить</button>
        </form>
    {% endif %}
{% endblock %}