source/accounts/urls.py
from django.urls import path, include
from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>", accounts_views.UserDetailView.as_view(), name="profile"),
    path('<int:pk>/change/', accounts_views.UserChangeView.as_view(), name='change'),
    path("<int:pk>/change-password/", accounts_views.UserPasswordChangeView.as_view(), name="change_password")
]

source/tractor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views

app_name = "webapp"

urlpatterns = [
    path("", webapp_views.IndexView.as_view(), name="index"),
    path("crane/", webapp_views.CraneView.as_view(), name="crane"),
    path("excavator/", webapp_views.ExcavatorView.as_view(), name="excavator"),
    path("truck/", webapp_views.TruckView.as_view(), name="truck"),
    path("lorry/", webapp_views.LorryView.as_view(), name="lorry"),
    path("small_truck/", webapp_views.SmallTrackView.as_view(), name="small_truck"),
    path("manipulator/", webapp_views.ManipulatorTrackView.as_view(), name="manipulator"),
    path("loader/", webapp_views.LoaderTrackView.as_view(), name="loader"),
    path("build_technique/", webapp_views.BuildTechniqueView.as_view(), name="build_technique"),
    path("tractor/", webapp_views.TractorView.as_view(), name="tractor"),
    path("other_technique/", webapp_views.OtherTechniqueView.as_view(), name="other_technique"),
    path("technique/create/", webapp_views.TechniqueCreateView.as_view(), name="technique_create"),
    path("technique/<int:pk>/change-status/", webapp_views.TechniqueStatusChangeView.as_view(), name="change_status"),
    path("technique/<int:pk>/", webapp_views.TechniqueDetailView.as_view(), name="technique_detail"),
    path("technique/<int:pk>/edit/", webapp_views.TechniqueEditView.as_view(), name="technique_edit"),
    path("technique/<int:pk>/delete/", webapp_views.TechniqueDeleteView.as_view(), name="technique_delete"),
    path("technique/<int:pk>/order/create/", webapp_views.OrderCreateView.as_view(), name="order_create"),
    path("technique/<int:pk>/order/delete/", webapp_views.OrderDeleteView.as_view(), name="order_delete"),
    path("technique/<int:pk>/comment/create/", webapp_views.CommentCreateView.as_view(), name="comment_create")
]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Категория")
    title = models.CharField(max_length=150, verbose_name="Наименование")

    def __str__(self):
        return self.title


class Technique(models.Model):
    price_choices =[("час", "час"), ("рейс", "рейс"), ("км", "км"), ("куб.м.", "куб.м."), ("кг", "кг")]
    status_choices =[("свободен", "свободен"), ("занят", "занят")]

    advertiser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор объявления", related_name="techniques")
    category = models.ForeignKey("webapp.Category", on_delete=models.CASCADE, verbose_name="Категория", related_name="Техника")
    name = models.CharField(max_length=150, verbose_name="Наименование")
    foto = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Фото техники")
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость услуги")
    price_description = models.CharField(max_length=50, choices=price_choices, default="час", verbose_name="Описание стоимости")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    status = models.CharField(max_length=30, choices=status_choices, default="свободен", verbose_name="Статус")
    qty = models.PositiveIntegerField(verbose_name="Количество часов со скидкой")
    sale_price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость услуги со скидкой")
    is_active = models.BooleanField(default=True, verbose_name="Активный")

    def __str__(self):
        return f"{self.pk} - {self.category.name}"


class Order(models.Model):
    technique = models.ForeignKey("webapp.Technique", on_delete=models.CASCADE,
                                  verbose_name="Заявка на технику", related_name="orders")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    start_time = models.DateTimeField(null=True, blank=True, verbose_name="Время начало")
    end_time = models.DateTimeField(null=True, blank=True, verbose_name="Время конца")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    offered_price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Предлагаемая цена")


class Comment(models.Model):
    technique = models.ForeignKey("webapp.Technique", on_delete=models.CASCADE,
                                  verbose_name="Комментарий на технику", related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    text = models.TextField(max_length=3000, verbose_name="Комментарий")

    def __str__(self):
        return f"{self.pk} - {self.author}"

source/webapp/forms.py
from django import forms

from webapp.models import Order, Comment, Technique


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["technique", "author"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["technique", "author"]


class TechniqueStatusForm(forms.ModelForm):
    class Meta:
        model = Technique
        exclude = ["advertiser", "category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]



class SearchForm(forms.Form):
    q = forms.CharField(max_length=100, required=False, label="Поиск")

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.http import urlencode
from django.views import View
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from accounts.admin import User
from webapp.forms import TechniqueStatusForm, SearchForm
from webapp.models import Technique


class IndexView(ListView):
    model = User
    template_name = "ads/index.html"
    context_object_name = "users"
    ordering = ["username"]

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"q": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(username__icontains=self.search_value) | Q(techniques__category__name=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["q"]


class CraneView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="truck crane")
        return render(request, "ads/technique.html", {"techniques": techniques})

class ExcavatorView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="excavator")
        return render(request, "ads/technique.html", {"techniques": techniques})

class TruckView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="truck")
        return render(request, "ads/technique.html", {"techniques": techniques})


class LorryView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="lorry")
        return render(request, "ads/technique.html", {"techniques": techniques})


class SmallTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="small track")
        return render(request, "ads/technique.html", {"techniques": techniques})


class LoaderTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="loader")
        return render(request, "ads/technique.html", {"techniques": techniques})


class ManipulatorTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="manipulator")
        return render(request, "ads/technique.html", {"techniques": techniques})


class BuildTechniqueView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="build technique")
        return render(request, "ads/technique.html", {"techniques": techniques})


class TractorView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="tractor")
        return render(request, "ads/technique.html", {"techniques": techniques})


class OtherTechniqueView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="other technique")
        return render(request, "ads/technique.html", {"techniques": techniques})


class TechniqueDetailView(DetailView):
    model = Technique
    template_name = "ads/detail.html"


class TechniqueCreateView(CreateView):
    model = Technique
    fields = ["category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]
    template_name = "ads/create.html"

    def form_valid(self, form):
        form.instance.advertiser = self.request.user
        return super(TechniqueCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("webapp:index")


class TechniqueEditView(UserPassesTestMixin, UpdateView):
    model = Technique
    fields = ["category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]
    template_name = "ads/edit.html"

    def test_func(self):
        return self.request.user == self.get_object().advertiser or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("webapp:technique_detail", kwargs={"pk": self.get_object().pk})


class TechniqueDeleteView(UserPassesTestMixin, DeleteView):
    model = Technique
    template_name = "ads/detail.html"

    def test_func(self):
        return self.request.user == self.get_object().advertiser or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("webapp:index")


class TechniqueStatusChangeView(UserPassesTestMixin, View):

    def test_func(self):
        technique = get_object_or_404(Technique, pk=self.kwargs["pk"])
        return self.request.user == technique.advertiser or self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        form = TechniqueStatusForm()
        return render(request, "ads/detail.html", {"form": form})

    def post(self, request, *args, **kwargs):
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        technique.status = request.POST.get('status')
        technique.save()
        return render(request, "ads/detail.html", {"technique": technique})

source/webapp/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from webapp.forms import CommentForm
from webapp.models import Comment, Technique


class CommentCreateView(View):
    def get(self, request, *args, **kwargs):
        form = CommentForm()
        return render(request, "comment/create.html", {"form": form, "pk":kwargs["pk"]})
    def post(self, request, *args, **kwargs):
        form = CommentForm(data=request.POST)
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        user = technique.advertiser
        if form.is_valid():
            comment = Comment.objects.create(
                technique=technique,
                author=user,
                text=form.cleaned_data["text"])

            return redirect("webapp:technique_detail", pk=comment.technique.pk)
        else:
            return render(request, "comment/create.html", {"form": form})

source/webapp/views/order_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import DeleteView

from webapp.models import Order, Technique
from webapp.forms import OrderForm


class OrderCreateView(View):
    def get(self, request, *args, **kwargs):
        form = OrderForm()
        return render(request, "ads/detail.html", {"form": form})
    def post(self, request, *args, **kwargs):
        form = OrderForm(data=request.POST)
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        user = technique.advertiser
        if form.is_valid():
            order = Order.objects.create(
                technique=technique,
                author=user,
                start_time=form.cleaned_data["start_time"],
                end_time=form.cleaned_data["end_time"],
                description=form.cleaned_data["description"],
                offered_price=form.cleaned_data["offered_price"])

            return redirect("webapp:technique_detail", pk=order.technique.pk)
        else:
            return render(request, "ads/detail.html", {"form": form, "technique": technique})


class OrderDeleteView(UserPassesTestMixin, DeleteView):
    model = Order
    template_name = "user_detail.html"

    def test_func(self):
        return self.request.user == self.get_object().author or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("accounts:profile")

source/webapp/templates/partial/header.html
{% csrf_token %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url "webapp:index" %}">
                <img src="https://cs.global-trace.ru/DgABAIQAzQEYAczc_8P7Dw/dhDwQoyUPUlGbkjWl3TDbQ/sv/image/f7/92/53/624078/4587/KOMATSU%20WB97S%20300%D1%85300.png?1519743343"
                     width="70px" height="70px" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">

                <li class="nav-item">
                  <a class="btn btn-outline-info" href="{% url "webapp:index" %}">Все пользователи</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="btn btn-outline-info" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Услуги грзоперевозок ↓
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url "webapp:truck" %}">Фуры/Тягачи</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:lorry" %}">Грузовики</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:small_truck" %}">Бытовые грузоперевозки</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="btn btn-outline-info" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Услуги спецтехники ↓
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url "webapp:crane" %}">Краны</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:manipulator" %}">Манипуляторы</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:loader" %}">Погрузчики</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:excavator" %}">Эксковаторы</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:tractor" %}">Тракторы</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:build_technique" %}">Строительная техника</a></li>
                    <li><a class="dropdown-item" href="{% url "webapp:other_technique" %}">Прочая техника</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="btn btn-outline-info" href="{% url "webapp:technique_create" %}">Добавить объявление</a>
                </li>
                <li class="nav-item">
                    <a title="Личный кабинет" class="btn btn-outline-info" aria-current="page"
                       href="{% url "accounts:profile" user.pk %}">Привет! {{ user.username }}</a>

                </li>
                <li class="nav-item">
                    <form class="logout" action="{% url "accounts:logout" %}?next={{ request.get_full_path }}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-info">Выход</button>
                    </form>
                </li>
    {% else %}
                <li class="nav-item">
                    <p class="login_btn">
                        <a class="btn btn-primary" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Login</a>
                        <a class="btn btn-success" href="{% url "accounts:register" %}">Sign up</a>
                    </p>
              </ul>
            </div>
          </div>
    {% endif %}
</nav>

source/webapp/templates/partial/search_form.html
{% load crispy_forms_filters %}
<form class="searh" action="" method="get">
    {{ search_form|crispy }}
</form>



