source/tractor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views

app_name = "webapp"

urlpatterns = [
    path("", webapp_views.IndexView.as_view(), name="index"),
    path("crane/", webapp_views.CraneView.as_view(), name="crane"),
    path("excavator/", webapp_views.ExcavatorView.as_view(), name="excavator"),
    path("truck/", webapp_views.TruckView.as_view(), name="truck"),
    path("lorry/", webapp_views.LorryView.as_view(), name="lorry"),
    path("small_truck/", webapp_views.SmallTrackView.as_view(), name="small_truck"),
    path("manipulator/", webapp_views.ManipulatorTrackView.as_view(), name="manipulator"),
    path("loader/", webapp_views.LoaderTrackView.as_view(), name="loader"),
    path("build_technique/", webapp_views.BuildTechniqueView.as_view(), name="build_technique"),
    path("tractor/", webapp_views.TractorView.as_view(), name="tractor"),
    path("other_technique/", webapp_views.OtherTechniqueView.as_view(), name="other_technique"),
    path("technique/create/", webapp_views.TechniqueCreateView.as_view(), name="technique_create"),
    path("technique/<int:pk>/change-status/", webapp_views.TechniqueStatusChangeView.as_view(), name="change_status"),
    path("technique/<int:pk>/", webapp_views.TechniqueDetailView.as_view(), name="technique_detail"),
    path("technique/<int:pk>/edit/", webapp_views.TechniqueEditView.as_view(), name="technique_edit"),
    path("technique/<int:pk>/delete/", webapp_views.TechniqueDeleteView.as_view(), name="technique_delete"),
    path("technique/<int:pk>/order/create/", webapp_views.OrderCreateView.as_view(), name="order_create"),
    path("technique/<int:pk>/order/delete/", webapp_views.OrderDeleteView.as_view(), name="order_delete"),
    path("technique/<int:pk>/comment/create/", webapp_views.CommentCreateView.as_view(), name="comment_create")
]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Категория")
    title = models.CharField(max_length=150, verbose_name="Наименование")

    def __str__(self):
        return self.title


class Technique(models.Model):
    price_choices =[("час", "час"), ("рейс", "рейс"), ("км", "км"), ("куб.м.", "куб.м."), ("кг", "кг")]
    status_choices =[("свободен", "свободен"), ("занят", "занят")]

    advertiser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор объявления", related_name="techniques")
    category = models.ForeignKey("webapp.Category", on_delete=models.CASCADE, verbose_name="Категория", related_name="Техника")
    name = models.CharField(max_length=150, verbose_name="Наименование")
    foto = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Фото техники")
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость услуги")
    price_description = models.CharField(max_length=50, choices=price_choices, default="час", verbose_name="Описание стоимости")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    status = models.CharField(max_length=30, choices=status_choices, default="свободен", verbose_name="Статус")
    qty = models.PositiveIntegerField(verbose_name="Количество часов со скидкой")
    sale_price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость услуги со скидкой")
    is_active = models.BooleanField(default=True, verbose_name="Активный")

    def __str__(self):
        return f"{self.pk} - {self.category.name}"


class Order(models.Model):
    technique = models.ForeignKey("webapp.Technique", on_delete=models.CASCADE,
                                  verbose_name="Заявка на технику", related_name="orders")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    start_time = models.DateTimeField(null=True, blank=True, verbose_name="Время начало")
    end_time = models.DateTimeField(null=True, blank=True, verbose_name="Время конца")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    offered_price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Предлагаемая цена")


class Comment(models.Model):
    technique = models.ForeignKey("webapp.Technique", on_delete=models.CASCADE,
                                  verbose_name="Комментарий на технику", related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    text = models.TextField(max_length=3000, verbose_name="Комментарий")

    def __str__(self):
        return f"{self.pk} - {self.author}"

source/webapp/forms.py
from django import forms

from webapp.models import Order, Comment, Technique


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["technique", "author"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["technique", "author"]


class TechniqueStatusForm(forms.ModelForm):
    class Meta:
        model = Technique
        exclude = ["advertiser", "category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]



class SearchForm(forms.Form):
    q = forms.CharField(max_length=100, required=False, label="Поиск")

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.http import urlencode
from django.views import View
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from accounts.admin import User
from webapp.forms import TechniqueStatusForm, SearchForm
from webapp.models import Technique


class IndexView(ListView):
    model = User
    template_name = "ads/index.html"
    context_object_name = "users"
    ordering = ["username"]

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"q": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(username__icontains=self.search_value) | Q(techniques__category__name=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["q"]


class CraneView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="truck crane")
        return render(request, "ads/technique.html", {"techniques": techniques})

class ExcavatorView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="excavator")
        return render(request, "ads/technique.html", {"techniques": techniques})

class TruckView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="truck")
        return render(request, "ads/technique.html", {"techniques": techniques})


class LorryView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="lorry")
        return render(request, "ads/technique.html", {"techniques": techniques})


class SmallTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="small track")
        return render(request, "ads/technique.html", {"techniques": techniques})


class LoaderTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="loader")
        return render(request, "ads/technique.html", {"techniques": techniques})


class ManipulatorTrackView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="manipulator")
        return render(request, "ads/technique.html", {"techniques": techniques})


class BuildTechniqueView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="build technique")
        return render(request, "ads/technique.html", {"techniques": techniques})


class TractorView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="tractor")
        return render(request, "ads/technique.html", {"techniques": techniques})


class OtherTechniqueView(View):
    ordering = ["is_active"]

    def get(self, request, *args, **kwargs):
        techniques = Technique.objects.filter(category__name="other technique")
        return render(request, "ads/technique.html", {"techniques": techniques})


class TechniqueDetailView(DetailView):
    model = Technique
    template_name = "ads/detail.html"


class TechniqueCreateView(CreateView):
    model = Technique
    fields = ["category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]
    template_name = "ads/create.html"

    def form_valid(self, form):
        form.instance.advertiser = self.request.user
        return super(TechniqueCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("webapp:index")


class TechniqueEditView(UserPassesTestMixin, UpdateView):
    model = Technique
    fields = ["category", "name", "foto", "price", "price_description", "description", "sale_price", "qty"]
    template_name = "ads/edit.html"

    def test_func(self):
        return self.request.user == self.get_object().advertiser or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("webapp:technique_detail", kwargs={"pk": self.get_object().pk})


class TechniqueDeleteView(UserPassesTestMixin, DeleteView):
    model = Technique
    template_name = "ads/detail.html"

    def test_func(self):
        return self.request.user == self.get_object().advertiser or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("webapp:index")


class TechniqueStatusChangeView(UserPassesTestMixin, View):

    def test_func(self):
        technique = get_object_or_404(Technique, pk=self.kwargs["pk"])
        return self.request.user == technique.advertiser or self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        form = TechniqueStatusForm()
        return render(request, "ads/detail.html", {"form": form})

    def post(self, request, *args, **kwargs):
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        technique.status = request.POST.get('status')
        technique.save()
        return render(request, "ads/detail.html", {"technique": technique})

source/webapp/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from webapp.forms import CommentForm
from webapp.models import Comment, Technique


class CommentCreateView(View):
    def get(self, request, *args, **kwargs):
        form = CommentForm()
        return render(request, "comment/create.html", {"form": form, "pk":kwargs["pk"]})
    def post(self, request, *args, **kwargs):
        form = CommentForm(data=request.POST)
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        user = technique.advertiser
        if form.is_valid():
            comment = Comment.objects.create(
                technique=technique,
                author=user,
                text=form.cleaned_data["text"])

            return redirect("webapp:technique_detail", pk=comment.technique.pk)
        else:
            return render(request, "comment/create.html", {"form": form})

source/webapp/views/order_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import DeleteView

from webapp.models import Order, Technique
from webapp.forms import OrderForm


class OrderCreateView(View):
    def get(self, request, *args, **kwargs):
        form = OrderForm()
        return render(request, "ads/detail.html", {"form": form})
    def post(self, request, *args, **kwargs):
        form = OrderForm(data=request.POST)
        technique = get_object_or_404(Technique, pk=kwargs["pk"])
        user = technique.advertiser
        if form.is_valid():
            order = Order.objects.create(
                technique=technique,
                author=user,
                start_time=form.cleaned_data["start_time"],
                end_time=form.cleaned_data["end_time"],
                description=form.cleaned_data["description"],
                offered_price=form.cleaned_data["offered_price"])

            return redirect("webapp:technique_detail", pk=order.technique.pk)
        else:
            return render(request, "ads/detail.html", {"form": form, "technique": technique})


class OrderDeleteView(UserPassesTestMixin, DeleteView):
    model = Order
    template_name = "user_detail.html"

    def test_func(self):
        return self.request.user == self.get_object().author or self.request.user.is_superuser

    def get_success_url(self):
        return reverse("accounts:profile")

source/webapp/templates/ads/create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Новое объявление{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Создать новое объявление</h1>
        <form action="{% url "webapp:technique_create" %}" method="post" enctype="multipart/form-data">
           {% csrf_token %}
                <p>{{ form|crispy }}</p><br><br>
            <button class="btn btn-primary">Создать</button>
        </form>
    {% endif %}
{% endblock %}

source/webapp/templates/ads/detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title%} {{ technique.name }} {% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <div class="technique_detail">

        <div class="technique_detail_foto">
            {% if technique.foto %}
                <img src="{{ technique.foto.url }}" class="card-img-top" alt="...">
            {% else %}
                <img src="https://thumbs.dreamstime.com/z/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B8-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE-%D0%B0-%D0%B7%D0%BD%D0%B0%D1%87%D0%BA%D0%B0-%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5-%D1%8C%D0%BD%D0%BE%D0%B9-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8-44830229.jpg"
                     width="500" height="375" alt="">
            {% endif %}
        </div>
        <div class="technique_detail_data">
            <p>{{ technique.name }}</p>
            <p>Цена: {{ technique.price }} тенге за {{ technique.price_description }}</p>
            <p>Свыше {{ technique.qty }} {{ technique.price_description }}(ов) {{ technique.sale_price }} тенге</p>
            <p>Контакты: {{ technique.advertiser.profile.phone_number }}</p>
            {% if request.user.username != technique.advertiser.username %}
                <button class="btn btn-success">свободен</button>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                  Подать заявку
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Заявка на {{ technique.name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <form action="{% url "webapp:order_create" technique.pk %}" method="post">
                           {% csrf_token %}
                            <div class="order_form">
                                Начало заявки: <p><input type="datetime-local" name="start_time"></p>
                                Конец заявки: <p><input type="datetime-local" name="send_time"></p>
                                Описание:  <p><input type="text" name="description"></p>
                                Предлагаемая цена: <p><input type="integer" name="offered_price"></p>
                                <button class="btn btn-primary">Отправить заявку</button>
                            </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
            {% else %}
                {% if technique.status == "свободен" %}
                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop2">
                      {{ technique.status }}
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                              <form action="{% url "webapp:change_status" technique.pk %}" method="post">
                              {% csrf_token %}
                                <select class="form-select" aria-label="Default select example" name="status">
                                      <option value="свободен">свободен</option>
                                      <option value="занят">занят</option>
                                </select>
                                <button class="btn btn-primary">Поменять статус</button>
                              </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>


                          </div>
                        </div>
                      </div>
                    </div>

                {% else %}


                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                      {{ technique.status }}
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                              <form action="{% url "webapp:change_status" technique.pk %}" method="post">
                              {% csrf_token %}
                                <select class="form-select" aria-label="Default select example" name="status">
                                      <option value="свободен">свободен</option>
                                      <option value="занят">занят</option>
                                </select>
                                <button class="btn btn-primary">Поменять статус</button>
                              </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>


                          </div>
                        </div>
                      </div>
                    </div>

                {% endif %}


            {% endif %}
        </div>
        <div class="technique_detail_description">
            <p>{{ technique.description }}</p>
        </div>

    </div>
        {% if request.user.username == technique.advertiser.username %}
            <form action="{% url "webapp:technique_delete" technique.pk %}">
                <a class="btn btn-primary" href="{% url "webapp:technique_edit" technique.pk %}" class="card-link">Редактировать</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal3">
                  Удалить
                </button>
            </form>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Вы хотите удалить:</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    {{ technique.name }} ?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    <form action="{% url "webapp:technique_delete" technique.pk %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-primary btn-danger">Да</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        {% endif %}


    <hr>


    <a class="btn btn-primary" style="margin-top: 5px" href="{% url "webapp:comment_create" technique.pk %}">Добавить комментарий</a>
    {% if technique.comments %}
        {% for comment in technique.comments.all %}
            <div class="card" style="width: 48rem">
              <div class="card-header">
                {{ comment.author }}
              </div>
              <div class="card-body">
                <blockquote class="blockquote mb-0">
                  <p>{{ comment.text }}</p><br>
                </blockquote>
              </div>
            </div>
        {% endfor %}
    {% endif %}
{% endif %}
{% endblock %}

source/webapp/templates/ads/edit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Редактировать{{ technique.name }}{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Редактировать {{ technique.name }}</h1>
        <form action="{% url "webapp:technique_edit" technique.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <p>{{ form|crispy }}</p>
            <button class="btn btn-primary">Редактировать</button>
        </form>
    {% endif %}
{% endblock %}

source/webapp/templates/ads/index.html
{% extends "base.html" %}

{% block title %} Main page {% endblock %}

{% block content %}
{% include "partial/search_form.html" %}
{% if user.is_authenticated %}
    {% for user in users %}

        <div class="card mb-3" style="max-width: 1000px; border-radius: 65px">
          <div class="row g-0">
            <div class="col-md-4">
                {% if user.profile.avatar %}
                    <img class="card_avatar" src="{{ user.profile.avatar.url }}" class="card-img-top" alt="...">
                {% else %}
                    <img class="card_avatar" src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-vector-260nw-1725655669.jpg"
                         class="card-img-top">
                {% endif %}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                  <p>
                    <p>Контакты: {{ user.profile.phone_number }}</p>
                    <small class="text-muted">Техника:</small>
                    {% for technique in user.techniques.all %}
                        <p class="card_data">
                            {{ technique.category.title }}:
                            {{ technique.name }}
                            {% if technique.status == "свободен" %}
                                <button class="card_btn btn-success">{{ technique.status }}</button>
                            {% else %}
                                <button class="card_btn btn-danger">{{ technique.status }}</button>
                            {% endif %}
                        </p>
                    {% endfor %}
                  </p>
              </div>
            </div>
          </div>
        </div>

    {% endfor %}
{% endif %}
{% endblock %}

source/webapp/templates/ads/technique.html
{% extends "base.html" %}

{% block title %} Краны {% endblock %}

{% block content%}
{% if user.is_authenticated %}
    {% for technique in techniques %}
        <a href="{% url "webapp:technique_detail" technique.pk %}">
            <div class="card mb-3" style="max-width: 1000px;">
              <div class="row g-0">
                <div class="col-md-5">
                 {% if technique.foto %}
                  <img src="{{ technique.foto.url }}" class="img-fluid" alt="...">
                 {% else %}
                  <img src="https://thumbs.dreamstime.com/z/%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B8-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE-%D0%B0-%D0%B7%D0%BD%D0%B0%D1%87%D0%BA%D0%B0-%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D0%B5-%D1%8C%D0%BD%D0%BE%D0%B9-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8-44830229.jpg"
                      class="img-fluid" alt="">
                 {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body-technique">
                    <h5 class="card-title">{{ technique.name }}</h5>
                    <h5 class="card-title">Цена: {{ technique.price }}
                        <img src="https://cdn-icons-png.flaticon.com/512/1490/1490896.png" width="25" height="25"alt="">
                        за {{ technique.price_description }}</h5>
                        <p class="card-text">
                            <small class="text-muted">Автор: </small>
                            {{ technique.advertiser.username }}
                            <small class="text-muted">Контакты: </small>
                            {{ user.profile.phone_number }}<br>
                        </p></a>
                    {% if technique.status == "свободен" %}

                        <div class="dropdown">

                            <p class="btn btn-success">{{ technique.status }}</p>

                    {% else %}

                            <p class="btn btn-danger">{{ technique.status }}</p>

                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

    {% endfor %}
{% endif %}
{% endblock %}